# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainGui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(796, 537)
        MainWindow.setSizeIncrement(QtCore.QSize(1, 1))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 260, 521, 221))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalSlider = QtGui.QSlider(self.tab)
        self.horizontalSlider.setGeometry(QtCore.QRect(80, 10, 411, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.horizontalSlider_2 = QtGui.QSlider(self.tab)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(80, 50, 411, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 59, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 59, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.checkBox = QtGui.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(80, 90, 86, 20))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(160, 90, 101, 20))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(10, 90, 59, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.lineEdit = QtGui.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(80, 10, 113, 21))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 40, 113, 21))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.label_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.checkBox_3 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_3.setGeometry(QtCore.QRect(80, 80, 86, 20))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_4.setGeometry(QtCore.QRect(80, 100, 86, 20))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_5 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_5.setGeometry(QtCore.QRect(80, 120, 111, 20))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 80, 59, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.listWidget = QtGui.QListWidget(self.tab_3)
        self.listWidget.setGeometry(QtCore.QRect(20, 31, 141, 171))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 141, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(210, 30, 131, 21))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(210, 10, 141, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(210, 60, 59, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.checkBox_6 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_6.setGeometry(QtCore.QRect(220, 80, 121, 20))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.textBrowser = QtGui.QTextBrowser(self.tab_4)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 491, 171))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 10, 141, 21))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.pushButton = QtGui.QPushButton(self.tab_5)
        self.pushButton.setGeometry(QtCore.QRect(162, 10, 81, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tab_5)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 40, 491, 141))
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.listView = QtGui.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(670, 270, 111, 181))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.selectgold = QtGui.QListView(self.centralwidget)
        self.selectgold.setGeometry(QtCore.QRect(550, 270, 111, 181))
        self.selectgold.setProperty("isWrapping", False)
        self.selectgold.setObjectName(_fromUtf8("selectgold"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 250, 111, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(670, 250, 111, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.PushButtonAddGold = QtGui.QPushButton(self.centralwidget)
        self.PushButtonAddGold.setGeometry(QtCore.QRect(550, 460, 111, 21))
        self.PushButtonAddGold.setObjectName(_fromUtf8("PushButtonAddGold"))
        self.PushButtonAddGuess = QtGui.QPushButton(self.centralwidget)
        self.PushButtonAddGuess.setGeometry(QtCore.QRect(670, 460, 111, 20))
        self.PushButtonAddGuess.setObjectName(_fromUtf8("PushButtonAddGuess"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(19, 19, 761, 231))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 759, 229))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionImprt = QtGui.QAction(MainWindow)
        self.actionImprt.setObjectName(_fromUtf8("actionImprt"))
        self.actionAddGold = QtGui.QAction(MainWindow)
        self.actionAddGold.setCheckable(True)
        self.actionAddGold.setObjectName(_fromUtf8("actionAddGold"))
        self.menuFile.addAction(self.actionImprt)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_3.setText(_translate("MainWindow", "Width:", None))
        self.label_4.setText(_translate("MainWindow", "Height:", None))
        self.checkBox.setText(_translate("MainWindow", "Curved", None))
        self.checkBox_2.setText(_translate("MainWindow", "Anitaliasing", None))
        self.label_11.setText(_translate("MainWindow", "Edges:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Appearance", None))
        self.label_5.setText(_translate("MainWindow", "Label:", None))
        self.label_6.setText(_translate("MainWindow", "Token:", None))
        self.checkBox_3.setText(_translate("MainWindow", "Only Path", None))
        self.checkBox_4.setText(_translate("MainWindow", "Collaps", None))
        self.checkBox_5.setText(_translate("MainWindow", "Whole Words", None))
        self.label_7.setText(_translate("MainWindow", "Options:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Edge Filter", None))
        self.label_8.setText(_translate("MainWindow", "Show Properties", None))
        self.label_9.setText(_translate("MainWindow", "Token:", None))
        self.label_10.setText(_translate("MainWindow", "Options:", None))
        self.checkBox_6.setText(_translate("MainWindow", "Whole Words", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Token Filters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Description", None))
        self.pushButton.setText(_translate("MainWindow", "Search", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Search Corpus", None))
        self.label.setText(_translate("MainWindow", "Select Gold", None))
        self.label_2.setText(_translate("MainWindow", "Select Guess", None))
        self.PushButtonAddGold.setText(_translate("MainWindow", "Add", None))
        self.PushButtonAddGuess.setText(_translate("MainWindow", "Add", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionImprt.setText(_translate("MainWindow", "Imprt", None))
        self.actionAddGold.setText(_translate("MainWindow", "AddGold", None))
        self.actionAddGold.setToolTip(_translate("MainWindow", "Add Gold File", None))

